// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Dissociable/Couploan/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldID, id))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldIP, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUsername, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPassword, v))
}

// Rotating applies equality check predicate on the "rotating" field. It's identical to RotatingEQ.
func Rotating(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldRotating, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldType, vs...))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldIP, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v uint16) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPort, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldUsername, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldPassword, v))
}

// RotatingEQ applies the EQ predicate on the "rotating" field.
func RotatingEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldRotating, v))
}

// RotatingNEQ applies the NEQ predicate on the "rotating" field.
func RotatingNEQ(v bool) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldRotating, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.NotPredicates(p))
}
