// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dissociable/Couploan/ent/predicate"
	"github.com/Dissociable/Couploan/ent/proxyprovider"
)

// ProxyProviderDelete is the builder for deleting a ProxyProvider entity.
type ProxyProviderDelete struct {
	config
	hooks    []Hook
	mutation *ProxyProviderMutation
}

// Where appends a list predicates to the ProxyProviderDelete builder.
func (ppd *ProxyProviderDelete) Where(ps ...predicate.ProxyProvider) *ProxyProviderDelete {
	ppd.mutation.Where(ps...)
	return ppd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppd *ProxyProviderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ppd.sqlExec, ppd.mutation, ppd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ppd *ProxyProviderDelete) ExecX(ctx context.Context) int {
	n, err := ppd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppd *ProxyProviderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(proxyprovider.Table, sqlgraph.NewFieldSpec(proxyprovider.FieldID, field.TypeInt))
	if ps := ppd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ppd.mutation.done = true
	return affected, err
}

// ProxyProviderDeleteOne is the builder for deleting a single ProxyProvider entity.
type ProxyProviderDeleteOne struct {
	ppd *ProxyProviderDelete
}

// Where appends a list predicates to the ProxyProviderDelete builder.
func (ppdo *ProxyProviderDeleteOne) Where(ps ...predicate.ProxyProvider) *ProxyProviderDeleteOne {
	ppdo.ppd.mutation.Where(ps...)
	return ppdo
}

// Exec executes the deletion query.
func (ppdo *ProxyProviderDeleteOne) Exec(ctx context.Context) error {
	n, err := ppdo.ppd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{proxyprovider.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppdo *ProxyProviderDeleteOne) ExecX(ctx context.Context) {
	if err := ppdo.Exec(ctx); err != nil {
		panic(err)
	}
}
