// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Dissociable/Couploan/ent/predicate"
	"github.com/Dissociable/Couploan/ent/proxy"
	"github.com/Dissociable/Couploan/ent/proxyprovider"
)

// ProxyProviderQuery is the builder for querying ProxyProvider entities.
type ProxyProviderQuery struct {
	config
	ctx        *QueryContext
	order      []proxyprovider.OrderOption
	inters     []Interceptor
	predicates []predicate.ProxyProvider
	withProxy  *ProxyQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProxyProviderQuery builder.
func (ppq *ProxyProviderQuery) Where(ps ...predicate.ProxyProvider) *ProxyProviderQuery {
	ppq.predicates = append(ppq.predicates, ps...)
	return ppq
}

// Limit the number of records to be returned by this query.
func (ppq *ProxyProviderQuery) Limit(limit int) *ProxyProviderQuery {
	ppq.ctx.Limit = &limit
	return ppq
}

// Offset to start from.
func (ppq *ProxyProviderQuery) Offset(offset int) *ProxyProviderQuery {
	ppq.ctx.Offset = &offset
	return ppq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ppq *ProxyProviderQuery) Unique(unique bool) *ProxyProviderQuery {
	ppq.ctx.Unique = &unique
	return ppq
}

// Order specifies how the records should be ordered.
func (ppq *ProxyProviderQuery) Order(o ...proxyprovider.OrderOption) *ProxyProviderQuery {
	ppq.order = append(ppq.order, o...)
	return ppq
}

// QueryProxy chains the current query on the "proxy" edge.
func (ppq *ProxyProviderQuery) QueryProxy() *ProxyQuery {
	query := (&ProxyClient{config: ppq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ppq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ppq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(proxyprovider.Table, proxyprovider.FieldID, selector),
			sqlgraph.To(proxy.Table, proxy.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, proxyprovider.ProxyTable, proxyprovider.ProxyColumn),
		)
		fromU = sqlgraph.SetNeighbors(ppq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProxyProvider entity from the query.
// Returns a *NotFoundError when no ProxyProvider was found.
func (ppq *ProxyProviderQuery) First(ctx context.Context) (*ProxyProvider, error) {
	nodes, err := ppq.Limit(1).All(setContextOp(ctx, ppq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{proxyprovider.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ppq *ProxyProviderQuery) FirstX(ctx context.Context) *ProxyProvider {
	node, err := ppq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProxyProvider ID from the query.
// Returns a *NotFoundError when no ProxyProvider ID was found.
func (ppq *ProxyProviderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ppq.Limit(1).IDs(setContextOp(ctx, ppq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{proxyprovider.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ppq *ProxyProviderQuery) FirstIDX(ctx context.Context) int {
	id, err := ppq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProxyProvider entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProxyProvider entity is found.
// Returns a *NotFoundError when no ProxyProvider entities are found.
func (ppq *ProxyProviderQuery) Only(ctx context.Context) (*ProxyProvider, error) {
	nodes, err := ppq.Limit(2).All(setContextOp(ctx, ppq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{proxyprovider.Label}
	default:
		return nil, &NotSingularError{proxyprovider.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ppq *ProxyProviderQuery) OnlyX(ctx context.Context) *ProxyProvider {
	node, err := ppq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProxyProvider ID in the query.
// Returns a *NotSingularError when more than one ProxyProvider ID is found.
// Returns a *NotFoundError when no entities are found.
func (ppq *ProxyProviderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ppq.Limit(2).IDs(setContextOp(ctx, ppq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{proxyprovider.Label}
	default:
		err = &NotSingularError{proxyprovider.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ppq *ProxyProviderQuery) OnlyIDX(ctx context.Context) int {
	id, err := ppq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProxyProviders.
func (ppq *ProxyProviderQuery) All(ctx context.Context) ([]*ProxyProvider, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryAll)
	if err := ppq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProxyProvider, *ProxyProviderQuery]()
	return withInterceptors[[]*ProxyProvider](ctx, ppq, qr, ppq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ppq *ProxyProviderQuery) AllX(ctx context.Context) []*ProxyProvider {
	nodes, err := ppq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProxyProvider IDs.
func (ppq *ProxyProviderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ppq.ctx.Unique == nil && ppq.path != nil {
		ppq.Unique(true)
	}
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryIDs)
	if err = ppq.Select(proxyprovider.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ppq *ProxyProviderQuery) IDsX(ctx context.Context) []int {
	ids, err := ppq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ppq *ProxyProviderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryCount)
	if err := ppq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ppq, querierCount[*ProxyProviderQuery](), ppq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ppq *ProxyProviderQuery) CountX(ctx context.Context) int {
	count, err := ppq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ppq *ProxyProviderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ppq.ctx, ent.OpQueryExist)
	switch _, err := ppq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ppq *ProxyProviderQuery) ExistX(ctx context.Context) bool {
	exist, err := ppq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProxyProviderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ppq *ProxyProviderQuery) Clone() *ProxyProviderQuery {
	if ppq == nil {
		return nil
	}
	return &ProxyProviderQuery{
		config:     ppq.config,
		ctx:        ppq.ctx.Clone(),
		order:      append([]proxyprovider.OrderOption{}, ppq.order...),
		inters:     append([]Interceptor{}, ppq.inters...),
		predicates: append([]predicate.ProxyProvider{}, ppq.predicates...),
		withProxy:  ppq.withProxy.Clone(),
		// clone intermediate query.
		sql:  ppq.sql.Clone(),
		path: ppq.path,
	}
}

// WithProxy tells the query-builder to eager-load the nodes that are connected to
// the "proxy" edge. The optional arguments are used to configure the query builder of the edge.
func (ppq *ProxyProviderQuery) WithProxy(opts ...func(*ProxyQuery)) *ProxyProviderQuery {
	query := (&ProxyClient{config: ppq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ppq.withProxy = query
	return ppq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProxyProvider.Query().
//		GroupBy(proxyprovider.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ppq *ProxyProviderQuery) GroupBy(field string, fields ...string) *ProxyProviderGroupBy {
	ppq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProxyProviderGroupBy{build: ppq}
	grbuild.flds = &ppq.ctx.Fields
	grbuild.label = proxyprovider.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ProxyProvider.Query().
//		Select(proxyprovider.FieldName).
//		Scan(ctx, &v)
func (ppq *ProxyProviderQuery) Select(fields ...string) *ProxyProviderSelect {
	ppq.ctx.Fields = append(ppq.ctx.Fields, fields...)
	sbuild := &ProxyProviderSelect{ProxyProviderQuery: ppq}
	sbuild.label = proxyprovider.Label
	sbuild.flds, sbuild.scan = &ppq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProxyProviderSelect configured with the given aggregations.
func (ppq *ProxyProviderQuery) Aggregate(fns ...AggregateFunc) *ProxyProviderSelect {
	return ppq.Select().Aggregate(fns...)
}

func (ppq *ProxyProviderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ppq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ppq); err != nil {
				return err
			}
		}
	}
	for _, f := range ppq.ctx.Fields {
		if !proxyprovider.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ppq.path != nil {
		prev, err := ppq.path(ctx)
		if err != nil {
			return err
		}
		ppq.sql = prev
	}
	return nil
}

func (ppq *ProxyProviderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProxyProvider, error) {
	var (
		nodes       = []*ProxyProvider{}
		_spec       = ppq.querySpec()
		loadedTypes = [1]bool{
			ppq.withProxy != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProxyProvider).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProxyProvider{config: ppq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ppq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ppq.withProxy; query != nil {
		if err := ppq.loadProxy(ctx, query, nodes,
			func(n *ProxyProvider) { n.Edges.Proxy = []*Proxy{} },
			func(n *ProxyProvider, e *Proxy) { n.Edges.Proxy = append(n.Edges.Proxy, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ppq *ProxyProviderQuery) loadProxy(ctx context.Context, query *ProxyQuery, nodes []*ProxyProvider, init func(*ProxyProvider), assign func(*ProxyProvider, *Proxy)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ProxyProvider)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Proxy(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(proxyprovider.ProxyColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.proxy_proxy_provider
		if fk == nil {
			return fmt.Errorf(`foreign-key "proxy_proxy_provider" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "proxy_proxy_provider" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ppq *ProxyProviderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ppq.querySpec()
	_spec.Node.Columns = ppq.ctx.Fields
	if len(ppq.ctx.Fields) > 0 {
		_spec.Unique = ppq.ctx.Unique != nil && *ppq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ppq.driver, _spec)
}

func (ppq *ProxyProviderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(proxyprovider.Table, proxyprovider.Columns, sqlgraph.NewFieldSpec(proxyprovider.FieldID, field.TypeInt))
	_spec.From = ppq.sql
	if unique := ppq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ppq.path != nil {
		_spec.Unique = true
	}
	if fields := ppq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxyprovider.FieldID)
		for i := range fields {
			if fields[i] != proxyprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ppq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ppq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ppq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ppq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ppq *ProxyProviderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ppq.driver.Dialect())
	t1 := builder.Table(proxyprovider.Table)
	columns := ppq.ctx.Fields
	if len(columns) == 0 {
		columns = proxyprovider.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ppq.sql != nil {
		selector = ppq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ppq.ctx.Unique != nil && *ppq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ppq.predicates {
		p(selector)
	}
	for _, p := range ppq.order {
		p(selector)
	}
	if offset := ppq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ppq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProxyProviderGroupBy is the group-by builder for ProxyProvider entities.
type ProxyProviderGroupBy struct {
	selector
	build *ProxyProviderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ppgb *ProxyProviderGroupBy) Aggregate(fns ...AggregateFunc) *ProxyProviderGroupBy {
	ppgb.fns = append(ppgb.fns, fns...)
	return ppgb
}

// Scan applies the selector query and scans the result into the given value.
func (ppgb *ProxyProviderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ppgb.build.ctx, ent.OpQueryGroupBy)
	if err := ppgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProxyProviderQuery, *ProxyProviderGroupBy](ctx, ppgb.build, ppgb, ppgb.build.inters, v)
}

func (ppgb *ProxyProviderGroupBy) sqlScan(ctx context.Context, root *ProxyProviderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ppgb.fns))
	for _, fn := range ppgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ppgb.flds)+len(ppgb.fns))
		for _, f := range *ppgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ppgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ppgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProxyProviderSelect is the builder for selecting fields of ProxyProvider entities.
type ProxyProviderSelect struct {
	*ProxyProviderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pps *ProxyProviderSelect) Aggregate(fns ...AggregateFunc) *ProxyProviderSelect {
	pps.fns = append(pps.fns, fns...)
	return pps
}

// Scan applies the selector query and scans the result into the given value.
func (pps *ProxyProviderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pps.ctx, ent.OpQuerySelect)
	if err := pps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProxyProviderQuery, *ProxyProviderSelect](ctx, pps.ProxyProviderQuery, pps, pps.inters, v)
}

func (pps *ProxyProviderSelect) sqlScan(ctx context.Context, root *ProxyProviderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pps.fns))
	for _, fn := range pps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
