-- Create "proxies" table
CREATE TABLE "proxies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "type" character varying NOT NULL, "ip" character varying NOT NULL, "port" smallint NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, "rotating" boolean NOT NULL DEFAULT false, PRIMARY KEY ("id"));
-- Create index "proxy_ip_port" to table: "proxies"
CREATE INDEX "proxy_ip_port" ON "proxies" ("ip", "port");
-- Create index "proxy_ip_port_username_password" to table: "proxies"
CREATE UNIQUE INDEX "proxy_ip_port_username_password" ON "proxies" ("ip", "port", "username", "password");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "contact" text NOT NULL, "role" character varying NOT NULL DEFAULT 'user', "key" character varying NOT NULL, "balance" bigint NOT NULL DEFAULT 0, "expires_at" timestamptz NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"));
-- Create index "user_contact" to table: "users"
CREATE INDEX "user_contact" ON "users" ("contact");
-- Create index "user_key" to table: "users"
CREATE INDEX "user_key" ON "users" ("key");
-- Create index "user_key_balance" to table: "users"
CREATE INDEX "user_key_balance" ON "users" ("key", "balance");
-- Create index "user_key_expires_at" to table: "users"
CREATE INDEX "user_key_expires_at" ON "users" ("key", "expires_at");
-- Create index "user_key_expires_at_balance" to table: "users"
CREATE INDEX "user_key_expires_at_balance" ON "users" ("key", "expires_at", "balance");
-- Create index "user_name" to table: "users"
CREATE INDEX "user_name" ON "users" ("name");
-- Create index "users_key_key" to table: "users"
CREATE UNIQUE INDEX "users_key_key" ON "users" ("key");
