name: Build

on:
  push:
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/couploan
          fetch-depth: 0
          fetch-tags: true
          token: ${{ secrets.PAT }}

      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: |
            ${{ github.workspace }}/couploan/go.sum

      -
        name: Go Tidy
        run: go mod tidy
        working-directory: ${{ github.workspace }}/couploan

      -
        name: Run GoReleaser for Pull Request
        uses: goreleaser/goreleaser-action@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          workdir: /couploan
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          workdir: /couploan
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
